# Generated by Django 4.2 on 2023-04-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spinny', '0003_alter_user_email_alter_user_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='boxes_in_this_week',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
