# Generated by Django 4.2 on 2023-04-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spinny', '0004_user_boxes_in_this_week_alter_user_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField()),
                ('breadth', models.IntegerField()),
                ('height', models.IntegerField()),
                ('area', models.IntegerField()),
                ('volume', models.IntegerField()),
                ('creator', models.CharField(max_length=30)),
                ('last_updated', models.CharField(max_length=30)),
                ('created_on', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_area', models.IntegerField()),
                ('average_volume', models.IntegerField()),
                ('total_boxes', models.IntegerField()),
                ('total_boxes_in_a_week', models.IntegerField()),
            ],
        ),
    ]
