# Generated by Django 4.2 on 2023-04-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spinny', '0005_box_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='total_boxes_in_a_week',
        ),
        migrations.RemoveField(
            model_name='user',
            name='boxes_in_this_week',
        ),
        migrations.AddField(
            model_name='box',
            name='current_week',
            field=models.IntegerField(default=14),
        ),
    ]
