# Generated by Django 4.2 on 2023-04-08 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spinny', '0006_remove_room_total_boxes_in_a_week_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='box',
            old_name='last_updated',
            new_name='last_updated_by',
        ),
        migrations.AddField(
            model_name='box',
            name='last_updated_on',
            field=models.DateField(default=datetime.date(2023, 4, 8)),
        ),
    ]
