# Generated by Django 4.2 on 2023-04-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spinny', '0007_rename_last_updated_box_last_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='yo',
            field=models.CharField(default='2', max_length=10),
        ),
    ]
