# Generated by Django 4.2 on 2023-04-09 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spinny', '0009_remove_box_yo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mobile_no',
        ),
        migrations.AlterField(
            model_name='box',
            name='last_updated_on',
            field=models.DateField(default=datetime.date(2023, 4, 9)),
        ),
    ]
