# Generated by Django 4.2 on 2023-04-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spinny', '0010_remove_user_mobile_no_alter_box_last_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=70),
        ),
    ]
